# Generated by Django 3.2.8 on 2021-10-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('BOOK', 'Book'), ('TOOL', 'Tool'), ('SERVICE', 'Service')], default='BOOK', max_length=20),
        ),
    ]
