# Generated by Django 3.2.8 on 2021-10-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Book', 'Book'), ('Tool', 'Tool'), ('Service', 'Service')], default='Book', max_length=20),
        ),
    ]
